school/apps/finance/urls.py
from django.urls import path

from .views import (
    InvoiceCreateView,
    InvoiceDeleteView,
    InvoiceDetailView,
    InvoiceListView,
    InvoiceUpdateView,
    ReceiptCreateView,
    ReceiptUpdateView,
    bulk_invoice,
)

urlpatterns = [
    path("list/", InvoiceListView.as_view(), name="invoice-list"),
    path("create/", InvoiceCreateView.as_view(), name="invoice-create"),
    path("<int:pk>/detail/", InvoiceDetailView.as_view(), name="invoice-detail"),
    path("<int:pk>/update/", InvoiceUpdateView.as_view(), name="invoice-update"),
    path("<int:pk>/delete/", InvoiceDeleteView.as_view(), name="invoice-delete"),
    path("receipt/create", ReceiptCreateView.as_view(), name="receipt-create"),
    path(
        "receipt/<int:pk>/update/", ReceiptUpdateView.as_view(), name="receipt-update"
    ),
    path("bulk-invoice/", bulk_invoice, name="bulk-invoice"),
]

school/school_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/apps/finance/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from apps.corecode.models import AcademicSession, AcademicTerm, StudentClass
from apps.students.models import Student


class Invoice(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    session = models.ForeignKey(AcademicSession, on_delete=models.CASCADE)
    term = models.ForeignKey(AcademicTerm, on_delete=models.CASCADE)
    class_for = models.ForeignKey(StudentClass, on_delete=models.CASCADE)
    balance_from_previous_term = models.IntegerField(default=0)
    status = models.CharField(
        max_length=20,
        choices=[("active", "Active"), ("closed", "Closed")],
        default="active",
    )

    class Meta:
        ordering = ["student", "term"]

    def __str__(self):
        return f"{self.student}"

    def balance(self):
        payable = self.total_amount_payable()
        paid = self.total_amount_paid()
        return payable - paid

    def amount_payable(self):
        items = InvoiceItem.objects.filter(invoice=self)
        total = 0
        for item in items:
            total += item.amount
        return total

    def total_amount_payable(self):
        return self.balance_from_previous_term + self.amount_payable()

    def total_amount_paid(self):
        receipts = Receipt.objects.filter(invoice=self)
        amount = 0
        for receipt in receipts:
            amount += receipt.amount_paid
        return amount

    def get_absolute_url(self):
        return reverse("invoice-detail", kwargs={"pk": self.pk})


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    amount = models.IntegerField()


class Receipt(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    amount_paid = models.IntegerField()
    date_paid = models.DateField(default=timezone.now)
    comment = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"Receipt on {self.date_paid}"

school/apps/finance/forms.py
from django.forms import inlineformset_factory, modelformset_factory

from .models import Invoice, InvoiceItem, Receipt

InvoiceItemFormset = inlineformset_factory(
    Invoice, InvoiceItem, fields=["description", "amount"], extra=1, can_delete=True
)

InvoiceReceiptFormSet = inlineformset_factory(
    Invoice,
    Receipt,
    fields=("amount_paid", "date_paid", "comment"),
    extra=0,
    can_delete=True,
)

Invoices = modelformset_factory(Invoice, exclude=(), extra=4)

school/apps/finance/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from apps.students.models import Student

from .forms import InvoiceItemFormset, InvoiceReceiptFormSet, Invoices
from .models import Invoice, InvoiceItem, Receipt


class InvoiceListView(LoginRequiredMixin, ListView):
    model = Invoice


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = Invoice
    fields = "__all__"
    success_url = "/finance/list"

    def get_context_data(self, **kwargs):
        context = super(InvoiceCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["items"] = InvoiceItemFormset(
                self.request.POST, prefix="invoiceitem_set"
            )
        else:
            context["items"] = InvoiceItemFormset(prefix="invoiceitem_set")
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["items"]
        self.object = form.save()
        if self.object.id != None:
            if form.is_valid() and formset.is_valid():
                formset.instance = self.object
                formset.save()
        return super().form_valid(form)


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = Invoice
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super(InvoiceDetailView, self).get_context_data(**kwargs)
        context["receipts"] = Receipt.objects.filter(invoice=self.object)
        context["items"] = InvoiceItem.objects.filter(invoice=self.object)
        return context


class InvoiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Invoice
    fields = ["student", "session", "term", "class_for", "balance_from_previous_term"]

    def get_context_data(self, **kwargs):
        context = super(InvoiceUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["receipts"] = InvoiceReceiptFormSet(
                self.request.POST, instance=self.object
            )
            context["items"] = InvoiceItemFormset(
                self.request.POST, instance=self.object
            )
        else:
            context["receipts"] = InvoiceReceiptFormSet(instance=self.object)
            context["items"] = InvoiceItemFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["receipts"]
        itemsformset = context["items"]
        if form.is_valid() and formset.is_valid() and itemsformset.is_valid():
            form.save()
            formset.save()
            itemsformset.save()
        return super().form_valid(form)


class InvoiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Invoice
    success_url = reverse_lazy("invoice-list")


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    fields = ["amount_paid", "date_paid", "comment"]
    success_url = reverse_lazy("invoice-list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        invoice = Invoice.objects.get(pk=self.request.GET["invoice"])
        obj.invoice = invoice
        obj.save()
        return redirect("invoice-list")

    def get_context_data(self, **kwargs):
        context = super(ReceiptCreateView, self).get_context_data(**kwargs)
        invoice = Invoice.objects.get(pk=self.request.GET["invoice"])
        context["invoice"] = invoice
        return context


class ReceiptUpdateView(LoginRequiredMixin, UpdateView):
    model = Receipt
    fields = ["amount_paid", "date_paid", "comment"]
    success_url = reverse_lazy("invoice-list")


class ReceiptDeleteView(LoginRequiredMixin, DeleteView):
    model = Receipt
    success_url = reverse_lazy("invoice-list")


@login_required
def bulk_invoice(request):
    return render(request, "finance/bulk_invoice.html")

school/apps/finance/templates/finance/bulk_invoice.html
{% extends 'base.html' %}


{% block title %}
Upload School Bills from excel
{% endblock title %}


{% block content %}

This page will cater for invoice upload from excel sheet


{% endblock content %}

school/apps/finance/templates/finance/invoice_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete invoice "{{ object }}"?</p>
    <p>All receipts attached to this invoice will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

school/apps/finance/templates/finance/invoice_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'invoice-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'invoice-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}



{% block content %}

<div class="row">
  <div class="col-sm-4">
    <h3>{{ object }} </h3>
    <h5>{{ object.session }} </h5>
    <h5>{{ object.term }} </h5>
    <h5>{{ object.class_for }} </h5>
    <h6>Status: {{ object.get_status_display }} </h6>
    <hr>
    <div>
      <h4>Expected Balance: {{ object.balance | intcomma }}</h4>
    </div>
  </div>
  <div class="col-sm-8">
    <table class="table table-sm table-bordered">
      Invoice Breakdown</br>
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>Description</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td>{{ forloop.counter }} </td>
          <td>{{ item.description }} </td>
          <td>{{ item.amount }} </td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td>Total Amount this term</td>
          <td>{{ object.amount_payable | intcomma}}</td>
        </tr>
        <tr>
          <td></td>
          <td>Balance from previous term</td>
          <td>{{ object.balance_from_previous_term | intcomma }}</td>
        </tr>
        <tr>
          <td></td>
          <td>Total Amount Payable</td>
          <td>{{ object.total_amount_payable | intcomma}}</td>
        </tr>
        <tr>
          <td></td>
          <td>Total Amount Paid</td>
          <td>{{ object.total_amount_paid | intcomma}}</td>
        </tr>

      </tfoot>
    </table>
  </div>
</div>

<hr>

<h5>Payment History</h5>
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th>S/N</th>
      <th>Amount Paid</th>
      <th>Date Paid</th>
      <th>Comment Paid</th>
    </tr>
  </thead>
  <tbody>
    {% for receipt in receipts %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ receipt.amount_paid}}</td>
      <td>{{ receipt.date_paid}}</td>
      <td>{{ receipt.comment}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock content %}

school/apps/finance/templates/finance/invoice_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}

{% if object %}
Update invoice {{ object }}
{% else %}
Add new invoice
{% endif %}

{% endblock title %}


{% block content %}

<form method="POST">
  {% csrf_token %}

  <div class="row">
    <div class="col-sm-6">
      {% for field in form %}
      <div class="form-group row">
        <label class="col col-form-label" for="{{ field.auto_id }}">
          {{ field.label }}
          {% for error in field.errors %}
          <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
          {% endfor %}
        </label>
        <div class="col">
          {{ field | add_class:"form-control"}}
          {% if field.help_text %}
          <small>{{ field.help_text|safe }}</small>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="col-sm-6 callout callout-info">
      {{ items.management_form }}
      <div class="text-center">FEE STRUCTURE</div>
      <div class="row">
        <div class="col"><strong>Fee Type</strong></div>
        <div class="col"><strong>Amount</strong></div>
      </div>
      {% for item in items %}
      <div class="form-group row items-group">
        {{ item.id}}
        <div class="col">{{ item.description | add_class:"form-control"}}</div>
        <div class="col">{{ item.amount | add_class:"form-control"}}</div>
      </div>
      {% endfor %}
    </div>
  </div>


  {% if object %}
    <h4>RECEIPTS</h4>
    <table class="table table-sm">
      {{ receipts.management_form }}
      <thead class="thead-light">
        <tr>
          <th>Amount Paid</th>
          <th>Date Paid</th>
          <th>Comment</th>
          <th><i class="fa fa-trash"></i></th>
        </tr>
      </thead>
      <tbody>
        {% for receipt in receipts %}
        {% for hidden in receipt.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        <tr>
          {% for field in receipt.visible_fields %}
          <td>{{ field | add_class:"form-control form-control-sm"}}</td>
          {% endfor %}
        </tr>
        {% endfor %}

      </tbody>
    </table>
  {% endif %}

  {% if object %}
  <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
  <input type="submit" class="btn btn-primary" value="Add new invoice">
  {% endif %}
</form>

<hr>


{% endblock content %}

{% block morejs %}
<script>
  $(".items-group").formset(
    {
      prefix: '{{ items.prefix }}',
      deleteText: "<div class='btn btn-danger btn-circle'><i class='fas fa-trash'></i></div>",
      addText: "<div class='btn btn-success btn-circle'><i class='fas fa-plus'></i></div>"
    }
  )
</script>
{% endblock morejs %}

school/apps/finance/templates/finance/invoice_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}invoices{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'invoice-create' %}"><i
    class="fas fa-plus"></i> New Invoice</a>
<a class="btn btn-primary" href="{% url 'bulk-invoice' %}"><i
    class="fas fa-upload"></i> Bulk Invoice</a>
{% endblock breadcrumb %}

{% block content %}
  <div class="table-responsive">
    <table id="invoicetable" class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>invoice</th>
          <th>Session-term</th>
          <th>Total Payable</th>
          <th>Total Paid</th>
          <th>Balance</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        {% for invoice in object_list %}
          <tr class='clickable-row' data-href="{% url 'invoice-detail' invoice.id %}">
            <td>{{ forloop.counter}}</td>
            <td>{{ invoice}}</td>
            <td>{{ invoice.session}}-{{ invoice.term}}</td>
            <td>{{ invoice.total_amount_payable | intcomma }}</td>
            <td>{{ invoice.total_amount_paid | intcomma }}</td>
            <td>{{ invoice.balance | intcomma }}</td>
            <td><a class="btn btn-success btn-sm"
                href="{% url 'receipt-create' %}?invoice={{ invoice.id }}">Add new
                receipt</a></td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
{% endblock content %}


{% block morejs %}
<script>
   $('#invoicetable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}

school/apps/finance/templates/finance/receipt_form.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

<div class="row">
  <div class="col-8">
    <form action="" method="POST">
      {% csrf_token %}

      {% include 'corecode/form_snippet.html' %}

      <input type="submit" class="btn btn-primary" value="Add payment">

    </form>
  </div>

  <div class="col-4">
    <div class="alert alert-info" role="alert">
      <h3>INVOICE</h3>
      <p>{{invoice | upper}}</p>
      <hr>
      <ul>

        <li>Session: {{ invoice.session }}</li>
        <li>Term: {{ invoice.term }}</li>
        <li>Class: {{ invoice.class_for }}</li>
        <li>Total Amount Payable: {{invoice.total_amount_payable | intcomma }}
        </li>
        <li>Total Amount Paid: {{ invoice.total_amount_paid | intcomma }}</li>
        <li><strong>Balance: {{invoice.balance | intcomma }}</strong></li>
      </ul>
    </div>
  </div>
</div>



{% endblock content %}