school/apps/staffs/urls.py
from django.urls import path

from .views import (
    StaffCreateView,
    StaffDeleteView,
    StaffDetailView,
    StaffListView,
    StaffUpdateView,
)

urlpatterns = [
    path("list/", StaffListView.as_view(), name="staff-list"),
    path("<int:pk>/", StaffDetailView.as_view(), name="staff-detail"),
    path("create/", StaffCreateView.as_view(), name="staff-create"),
    path("<int:pk>/update/", StaffUpdateView.as_view(), name="staff-update"),
    path("<int:pk>/delete/", StaffDeleteView.as_view(), name="staff-delete"),
]

school/school_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/apps/staffs/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Staff(models.Model):
    STATUS = [("active", "Active"), ("inactive", "Inactive")]

    GENDER = [("male", "Male"), ("female", "Female")]

    current_status = models.CharField(max_length=10, choices=STATUS, default="active")
    surname = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    other_name = models.CharField(max_length=200, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default="male")
    date_of_birth = models.DateField(default=timezone.now)
    date_of_admission = models.DateField(default=timezone.now)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13, blank=True
    )

    address = models.TextField(blank=True)
    others = models.TextField(blank=True)

    def __str__(self):
        return f"{self.surname} {self.firstname} {self.other_name}"

    def get_absolute_url(self):
        return reverse("staff-detail", kwargs={"pk": self.pk})

school/apps/staffs/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Staff


class StaffListView(ListView):
    model = Staff


class StaffDetailView(DetailView):
    model = Staff
    template_name = "staffs/staff_detail.html"


class StaffCreateView(SuccessMessageMixin, CreateView):
    model = Staff
    fields = "__all__"
    success_message = "New staff successfully added"

    def get_form(self):
        """add date picker in forms"""
        form = super(StaffCreateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["others"].widget = widgets.Textarea(attrs={"rows": 1})
        return form


class StaffUpdateView(SuccessMessageMixin, UpdateView):
    model = Staff
    fields = "__all__"
    success_message = "Record successfully updated."

    def get_form(self):
        """add date picker in forms"""
        form = super(StaffUpdateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["others"].widget = widgets.Textarea(attrs={"rows": 1})
        return form


class StaffDeleteView(DeleteView):
    model = Staff
    success_url = reverse_lazy("staff-list")

school/apps/staffs/templates/staffs/staff_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this staff will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

school/apps/staffs/templates/staffs/staff_detail.html
{% extends 'base.html' %}


{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'staff-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'staff-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row">
      <div class="col-sm-4">
        <div>
          <h3>{{ object }} </h3>
          <h5>{{ object.current_class }} </h5>
          <h5>{{ object.get_gender_display }} </h5>
          <h5>{{ object.get_current_status_display }} </h5>
        </div>
      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date of Birth
            </label>
            <div class="col">
              {{ object.date_of_birth }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
               Mobile Number
            </label>
            <div class="col">
              {{ object.mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Address
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Comments
            </label>
            <div class="col">
              {{ object.others }}
            </div>
          </div>

        </div>

      </div>
    </div>




{% endblock content %}

school/apps/staffs/templates/staffs/staff_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new student
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new student">
  {% endif %}
</form>


{% endblock content %}

school/apps/staffs/templates/staffs/staff_list.html
{% extends 'base.html' %}

{% block title %}staffs{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'staff-create' %}"><i
    class="fas fa-plus"></i> New staff</a>
{% endblock breadcrumb %}

{% block content %}
  <table id="stafftable" class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>S/N</th>
        <th>Fullname</th>
        <th>Gender</th>
        <th>Mobile Phone Number</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>

      {% for staff in object_list %}
        <tr class='clickable-row' data-href="{% url 'staff-detail' staff.id %}">
          <td>{{ forloop.counter}}</td>
          <td>{{ staff.surname}} {{staff.firstname }} {{staff.other_name }}</td>
          <td>{{ staff.get_gender_display}}</td>
          <td>{{ staff.parent_mobile_number}}</td>
          <td>{{ staff.get_current_status_display}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
{% endblock content %}


{% block morejs %}
<script>
   $('#stafftable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}